### ISSUE TITLE
Initial Release Checklist

### ISSUE THREAD

**Issue by raphydaphy** [raphydaphy/ArcaneMagic#4]
In order of importance

- [ ] Resolve https://github.com/Prospector/Silk/issues/6
- [ ] Add a display for active dagger effect timer/cooldown
- [ ] Make a logo
- [ ] Sound Effects & Particles for the Dagger
- [ ] Sounds for Crystal Infuser
- [ ] Wait for https://github.com/FabricMC/fabric/pull/65 for Analyzer/Mixer models
- [ ] Particles for Altar
- [ ] Improve Smelter animation with other texture
